#!/bin/bash

cppcheck --error-exitcode=9 --inline-suppr --suppress=missingIncludeSystem -I .  --enable=all . || exit 1

if [[ "$1" == "debug" ]]; then
    CPPOPT="-Og -g"
    ANIMATEOPT=test
else
    CPPOPT="-O3"
    ANIMATEOPT=$1
fi
g++ ${CPPOPT} -Wall -Werror -o animate animate.cpp || exit 1

./animate ${ANIMATEOPT} || exit 1
exit 0
