#!/bin/bash

cppcheck --error-exitcode=9 --inline-suppr --suppress=missingIncludeSystem -I . --enable=all circuit_test.cpp || exit 1

if [[ "$1" == "debug" ]]; then
    CPPOPT="-Og -g"
else
    CPPOPT="-O3"
fi
g++ ${CPPOPT} -Wall -Werror -o circuit_test circuit_test.cpp || exit 1

./circuit_test || exit 1
exit 0
