#!/bin/bash

cppcheck --error-exitcode=9 --inline-suppr --suppress=missingIncludeSystem -I . -I /usr/local/include  --enable=all viewlog.cpp || exit 1

if [[ "$1" == "debug" ]]; then
    CPPOPT="-Og -g"
else
    CPPOPT="-O3"
fi
g++ ${CPPOPT} -Wall -Werror -o viewlog viewlog.cpp -l raylib -l pthread -l dl || exit 1

./viewlog ../hardware/data/cvn1_r0.csv || exit 1
exit 0
